# <center>JSONiq Update Facility sandbox</center>

The following cell is meant for Google Colab, which does not have the right Java version.

In [1]:
# We make sure Java 17 is installed.
!java -version

openjdk version "17.0.19" 2026-04-21
OpenJDK Runtime Environment (build 17.0.19+10-1-22.04.2-Ubuntu)
OpenJDK 64-Bit Server VM (build 17.0.19+10-1-22.04.2-Ubuntu, mixed mode, sharing)

In [2]:
!pip install jsoniq

Collecting jsoniq
  Downloading jsoniq-2.1.7-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: pyspark==4.0.2 in /usr/local/lib/python3.12/dist-packages (from jsoniq) (4.0.2)
Requirement already satisfied: pandas>=2.2 in /usr/local/lib/python3.12/dist-packages (from jsoniq) (2.2.2)
Collecting delta-spark==4.0 (from jsoniq)
  Downloading delta_spark-4.0.0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: importlib-metadata>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from delta-spark==4.0->jsoniq) (8.7.1)
Requirement already satisfied: py4j<0.10.9.10,>=0.10.9.7 in /usr/local/lib/python3.12/dist-packages (from pyspark==4.0.2->jsoniq) (0.10.9.9)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2->jsoniq) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2->jsoniq) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2->jsoniq) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2->jsoniq) (2026.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata>=1.0.0->delta-spark==4.0->jsoniq) (4.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2->jsoniq) (1.17.0)
Downloading jsoniq-2.1.7-py3-none-any.whl (72.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.3/72.3 MB 10.7 MB/s eta 0:00:00
Downloading delta_spark-4.0.0-py3-none-any.whl (39 kB)
Installing collected packages: delta-spark, jsoniq
Successfully installed delta-spark-4.0.0 jsoniq-2.1.7

We now initialize a RumbleDB session and test that it works.

In [3]:
from jsoniq import RumbleSession

rumble = RumbleSession.builder.withDelta().getOrCreate();

print(rumble.jsoniq('{ "foo": [ 6*7 ] }').json());

[Info] Using RumbleDB jar file at: file:///usr/local/lib/python3.12/dist-packages/jsoniq/jars/rumbledb-2.1.7.jar
({'foo': [42]},)

For convenience, we also activate the JSONiq magic.

In [4]:
%load_ext jsoniqmagic

We create a new collection

In [5]:
%%jsoniq -u -t
create collection table("foo") with for $i in 1000000 to 3000000 return { "foo" : $i, "bar" : [ "Alice", "Bob", "Charlie" ] }

Updates applied successfully.
Response time: 20.72827124595642 ms

In [18]:
%%jsoniq -df
table("foo")

+-------+--------------------+-----------+----------+-----------------+--------+---------------+
|    foo|                 bar|    __rowID|__rowOrder|__mutabilityLevel|__pathIn|__tableLocation|
+-------+--------------------+-----------+----------+-----------------+--------+---------------+
|4000000|[Alice, Bob, Char...|17183869187|-2001000.0|                0|        |            foo|
|4000001|[Alice, Bob, Char...|17183869188|-2000999.0|                0|        |            foo|
|4000002|[Alice, Bob, Char...|17183869189|-2000998.0|                0|        |            foo|
|4000003|[Alice, Bob, Char...|17183869190|-2000997.0|                0|        |            foo|
|4000004|[Alice, Bob, Char...|17183869191|-2000996.0|                0|        |            foo|
|4000005|[Alice, Bob, Char...|17183869192|-2000995.0|                0|        |            foo|
|4000006|[Alice, Bob, Char...|17183869193|-2000994.0|                0|        |            foo|
|4000007|[Alice, Bob, Char...|17183869194|-2000993.0|                0|        |            foo|
|4000008|[Alice, Bob, Char...|17183869195|-2000992.0|                0|        |            foo|
|4000009|[Alice, Bob, Char...|17183869196|-2000991.0|                0|        |            foo|
|4000010|[Alice, Bob, Char...|17183869197|-2000990.0|                0|        |            foo|
|4000011|[Alice, Bob, Char...|17183869198|-2000989.0|                0|        |            foo|
|4000012|[Alice, Bob, Char...|17183869199|-2000988.0|                0|        |            foo|
|4000013|[Alice, Bob, Char...|17183869200|-2000987.0|                0|        |            foo|
|4000014|[Alice, Bob, Char...|17183869201|-2000986.0|                0|        |            foo|
|4000015|[Alice, Bob, Char...|17183869202|-2000985.0|                0|        |            foo|
|4000016|[Alice, Bob, Char...|17183869203|-2000984.0|                0|        |            foo|
|4000017|[Alice, Bob, Char...|17183869204|-2000983.0|                0|        |            foo|
|4000018|[Alice, Bob, Char...|17183869205|-2000982.0|                0|        |            foo|
|4000019|[Alice, Bob, Char...|17183869206|-2000981.0|                0|        |            foo|
+-------+--------------------+-----------+----------+-----------------+--------+---------------+
only showing top 20 rows

In [9]:
%%jsoniq -pdf
count(table("foo"))

   __value
0  2000001

We insert new data -- remember the snapshot semantics, all updates are computed against the original table, and then applied jointly.

In [12]:
%%jsoniq -u -t
insert for $i in 4000000 to 6000000 return { "foo" : $i, "bar" : [ "Alice", "Bob", "Charlie" ] }
  first into collection table("foo"),
insert for $i in 7000000 to 10000000 return { "foo" : $i, "bar" : [ "Alice", "Bob", "Charlie" ] }
  last into collection table("foo"),
insert for $i in 11000000 to 13000000 return { "foo" : $i, "bar" : [ "Alice", "Bob", "Charlie" ] }
  before table("foo")[position() eq 2] into collection,
insert for $i in 14000000 to 16000000 return { "foo" : $i, "bar" : [ "Alice", "Bob", "Charlie" ] }
  after table("foo")[position() eq 2] into collection

Updates applied successfully.
Response time: 94.80314445495605 ms

In [17]:
%%jsoniq -df
table("foo")

+-------+--------------------+-----------+----------+-----------------+--------+---------------+
|    foo|                 bar|    __rowID|__rowOrder|__mutabilityLevel|__pathIn|__tableLocation|
+-------+--------------------+-----------+----------+-----------------+--------+---------------+
|4000000|[Alice, Bob, Char...|17183869187|-2001000.0|                0|        |            foo|
|4000001|[Alice, Bob, Char...|17183869188|-2000999.0|                0|        |            foo|
|4000002|[Alice, Bob, Char...|17183869189|-2000998.0|                0|        |            foo|
|4000003|[Alice, Bob, Char...|17183869190|-2000997.0|                0|        |            foo|
|4000004|[Alice, Bob, Char...|17183869191|-2000996.0|                0|        |            foo|
|4000005|[Alice, Bob, Char...|17183869192|-2000995.0|                0|        |            foo|
|4000006|[Alice, Bob, Char...|17183869193|-2000994.0|                0|        |            foo|
|4000007|[Alice, Bob, Char...|17183869194|-2000993.0|                0|        |            foo|
|4000008|[Alice, Bob, Char...|17183869195|-2000992.0|                0|        |            foo|
|4000009|[Alice, Bob, Char...|17183869196|-2000991.0|                0|        |            foo|
|4000010|[Alice, Bob, Char...|17183869197|-2000990.0|                0|        |            foo|
|4000011|[Alice, Bob, Char...|17183869198|-2000989.0|                0|        |            foo|
|4000012|[Alice, Bob, Char...|17183869199|-2000988.0|                0|        |            foo|
|4000013|[Alice, Bob, Char...|17183869200|-2000987.0|                0|        |            foo|
|4000014|[Alice, Bob, Char...|17183869201|-2000986.0|                0|        |            foo|
|4000015|[Alice, Bob, Char...|17183869202|-2000985.0|                0|        |            foo|
|4000016|[Alice, Bob, Char...|17183869203|-2000984.0|                0|        |            foo|
|4000017|[Alice, Bob, Char...|17183869204|-2000983.0|                0|        |            foo|
|4000018|[Alice, Bob, Char...|17183869205|-2000982.0|                0|        |            foo|
|4000019|[Alice, Bob, Char...|17183869206|-2000981.0|                0|        |            foo|
+-------+--------------------+-----------+----------+-----------------+--------+---------------+
only showing top 20 rows

In [14]:
%%jsoniq -pdf
count(table("foo"))

    __value
0  11000005

We delete a record

In [19]:
%%jsoniq -u -t
delete table("foo")[$$.foo eq 1500000] from collection

Updates applied successfully.
Response time: 12.191509485244751 ms

In [20]:
%%jsoniq -df -t
count(table("foo"))

+--------+
| __value|
+--------+
|11000004|
+--------+

Response time: 1.0262038707733154 ms

We edit a record

In [21]:
%%jsoniq -u -t
edit table("foo")[$$.foo eq 1400000] into { "foo" : 22170000, "bar" : [ "Alice", "Bob", "Daniel" ] } in collection

Updates applied successfully.
Response time: 15.4900643825531 ms

In [22]:
%%jsoniq
table("foo")[$$.foo eq 22170000]

{
  "foo": 22170000,
  "bar": [
    "Alice",
    "Bob",
    "Daniel"
  ]
}

In [23]:
%%jsoniq -df -t
table("foo")

+-------+--------------------+-----------+----------+-----------------+--------+---------------+
|    foo|                 bar|    __rowID|__rowOrder|__mutabilityLevel|__pathIn|__tableLocation|
+-------+--------------------+-----------+----------+-----------------+--------+---------------+
|4000000|[Alice, Bob, Char...|17183869187|-2001000.0|                0|        |            foo|
|4000001|[Alice, Bob, Char...|17183869188|-2000999.0|                0|        |            foo|
|4000002|[Alice, Bob, Char...|17183869189|-2000998.0|                0|        |            foo|
|4000003|[Alice, Bob, Char...|17183869190|-2000997.0|                0|        |            foo|
|4000004|[Alice, Bob, Char...|17183869191|-2000996.0|                0|        |            foo|
|4000005|[Alice, Bob, Char...|17183869192|-2000995.0|                0|        |            foo|
|4000006|[Alice, Bob, Char...|17183869193|-2000994.0|                0|        |            foo|
|4000007|[Alice, Bob, Char...|17183869194|-2000993.0|                0|        |            foo|
|4000008|[Alice, Bob, Char...|17183869195|-2000992.0|                0|        |            foo|
|4000009|[Alice, Bob, Char...|17183869196|-2000991.0|                0|        |            foo|
|4000010|[Alice, Bob, Char...|17183869197|-2000990.0|                0|        |            foo|
|4000011|[Alice, Bob, Char...|17183869198|-2000989.0|                0|        |            foo|
|4000012|[Alice, Bob, Char...|17183869199|-2000988.0|                0|        |            foo|
|4000013|[Alice, Bob, Char...|17183869200|-2000987.0|                0|        |            foo|
|4000014|[Alice, Bob, Char...|17183869201|-2000986.0|                0|        |            foo|
|4000015|[Alice, Bob, Char...|17183869202|-2000985.0|                0|        |            foo|
|4000016|[Alice, Bob, Char...|17183869203|-2000984.0|                0|        |            foo|
|4000017|[Alice, Bob, Char...|17183869204|-2000983.0|                0|        |            foo|
|4000018|[Alice, Bob, Char...|17183869205|-2000982.0|                0|        |            foo|
|4000019|[Alice, Bob, Char...|17183869206|-2000981.0|                0|        |            foo|
+-------+--------------------+-----------+----------+-----------------+--------+---------------+
only showing top 20 rows
Response time: 8.57655954360962 ms

In [24]:
%%jsoniq -t
rename json table("foo")[1].foo as "bar2";

Response time: 19.79288148880005 ms

In [25]:
%%jsoniq -df -t
table("foo")

+-------+--------------------+-----------+----------+-----------------+--------+---------------+
|   bar2|                 bar|    __rowID|__rowOrder|__mutabilityLevel|__pathIn|__tableLocation|
+-------+--------------------+-----------+----------+-----------------+--------+---------------+
|4000000|[Alice, Bob, Char...|17183869187|-2001000.0|                0|        |            foo|
|4000001|[Alice, Bob, Char...|17183869188|-2000999.0|                0|        |            foo|
|4000002|[Alice, Bob, Char...|17183869189|-2000998.0|                0|        |            foo|
|4000003|[Alice, Bob, Char...|17183869190|-2000997.0|                0|        |            foo|
|4000004|[Alice, Bob, Char...|17183869191|-2000996.0|                0|        |            foo|
|4000005|[Alice, Bob, Char...|17183869192|-2000995.0|                0|        |            foo|
|4000006|[Alice, Bob, Char...|17183869193|-2000994.0|                0|        |            foo|
|4000007|[Alice, Bob, Char...|17183869194|-2000993.0|                0|        |            foo|
|4000008|[Alice, Bob, Char...|17183869195|-2000992.0|                0|        |            foo|
|4000009|[Alice, Bob, Char...|17183869196|-2000991.0|                0|        |            foo|
|4000010|[Alice, Bob, Char...|17183869197|-2000990.0|                0|        |            foo|
|4000011|[Alice, Bob, Char...|17183869198|-2000989.0|                0|        |            foo|
|4000012|[Alice, Bob, Char...|17183869199|-2000988.0|                0|        |            foo|
|4000013|[Alice, Bob, Char...|17183869200|-2000987.0|                0|        |            foo|
|4000014|[Alice, Bob, Char...|17183869201|-2000986.0|                0|        |            foo|
|4000015|[Alice, Bob, Char...|17183869202|-2000985.0|                0|        |            foo|
|4000016|[Alice, Bob, Char...|17183869203|-2000984.0|                0|        |            foo|
|4000017|[Alice, Bob, Char...|17183869204|-2000983.0|                0|        |            foo|
|4000018|[Alice, Bob, Char...|17183869205|-2000982.0|                0|        |            foo|
|4000019|[Alice, Bob, Char...|17183869206|-2000981.0|                0|        |            foo|
+-------+--------------------+-----------+----------+-----------------+--------+---------------+
only showing top 20 rows
Response time: 12.09342622756958 ms

In [26]:
%%jsoniq -u -t
delete collection table("foo")

Updates applied successfully.
Response time: 0.17138385772705078 ms

In [27]:
%%jsoniq -u -t
create collection delta-file("foobar") with for $i in 1000000 to 3000000 return { "foo" : $i, "bar" : [ "Alice", "Bob", "Charlie" ] }

Updates applied successfully.
Response time: 4.1448187828063965 ms

In [28]:
%%jsoniq -df -t
delta-file("foobar")

+-------+--------------------+-------+----------+-----------------+--------+--------------------+
|    foo|                 bar|__rowID|__rowOrder|__mutabilityLevel|__pathIn|     __tableLocation|
+-------+--------------------+-------+----------+-----------------+--------+--------------------+
|1000000|[Alice, Bob, Char...|      0|       0.0|                0|        |delta.`file:/cont...|
|1000001|[Alice, Bob, Char...|      1|       1.0|                0|        |delta.`file:/cont...|
|1000002|[Alice, Bob, Char...|      2|       2.0|                0|        |delta.`file:/cont...|
|1000003|[Alice, Bob, Char...|      3|       3.0|                0|        |delta.`file:/cont...|
|1000004|[Alice, Bob, Char...|      4|       4.0|                0|        |delta.`file:/cont...|
|1000005|[Alice, Bob, Char...|      5|       5.0|                0|        |delta.`file:/cont...|
|1000006|[Alice, Bob, Char...|      6|       6.0|                0|        |delta.`file:/cont...|
|1000007|[Alice, Bob, Char...|      7|       7.0|                0|        |delta.`file:/cont...|
|1000008|[Alice, Bob, Char...|      8|       8.0|                0|        |delta.`file:/cont...|
|1000009|[Alice, Bob, Char...|      9|       9.0|                0|        |delta.`file:/cont...|
|1000010|[Alice, Bob, Char...|     10|      10.0|                0|        |delta.`file:/cont...|
|1000011|[Alice, Bob, Char...|     11|      11.0|                0|        |delta.`file:/cont...|
|1000012|[Alice, Bob, Char...|     12|      12.0|                0|        |delta.`file:/cont...|
|1000013|[Alice, Bob, Char...|     13|      13.0|                0|        |delta.`file:/cont...|
|1000014|[Alice, Bob, Char...|     14|      14.0|                0|        |delta.`file:/cont...|
|1000015|[Alice, Bob, Char...|     15|      15.0|                0|        |delta.`file:/cont...|
|1000016|[Alice, Bob, Char...|     16|      16.0|                0|        |delta.`file:/cont...|
|1000017|[Alice, Bob, Char...|     17|      17.0|                0|        |delta.`file:/cont...|
|1000018|[Alice, Bob, Char...|     18|      18.0|                0|        |delta.`file:/cont...|
|1000019|[Alice, Bob, Char...|     19|      19.0|                0|        |delta.`file:/cont...|
+-------+--------------------+-------+----------+-----------------+--------+--------------------+
only showing top 20 rows
Response time: 6.958235025405884 ms

In [ ]:
%%jsoniq -u -t
insert for $i in 4000000 to 6000000 return { "foo" : $i, "bar" : [ "Alice", "Bob", "Charlie" ] }
  first into collection delta-file("foobar"),
insert for $i in 7000000 to 10000000 return { "foo" : $i, "bar" : [ "Alice", "Bob", "Charlie" ] }
  last into collection delta-file("foobar"),
insert for $i in 11000000 to 13000000 return { "foo" : $i, "bar" : [ "Alice", "Bob", "Charlie" ] }
  before delta-file("foobar")[position() eq 2] into collection,
insert for $i in 14000000 to 16000000 return { "foobar" : $i, "bar" : [ "Alice", "Bob", "Charlie" ] }
  after delta-file("foobar")[position() eq 2] into collection

In [ ]:
%%jsoniq -df -t
delta-file("foobar")

+-------+--------------------+-----------+----------+-----------------+--------+--------------------+
|    foo|                 bar|    __rowID|__rowOrder|__mutabilityLevel|__pathIn|     __tableLocation|
+-------+--------------------+-----------+----------+-----------------+--------+--------------------+
|4000000|[Alice, Bob, Char...|17183869187| -99999.95|                0|        |delta.`file:/User...|
|4000001|[Alice, Bob, Char...|17183869188|  -99999.9|                0|        |delta.`file:/User...|
|4000002|[Alice, Bob, Char...|17183869189| -99999.85|                0|        |delta.`file:/User...|
|4000003|[Alice, Bob, Char...|17183869190|  -99999.8|                0|        |delta.`file:/User...|
|4000004|[Alice, Bob, Char...|17183869191| -99999.75|                0|        |delta.`file:/User...|
|4000005|[Alice, Bob, Char...|17183869192|  -99999.7|                0|        |delta.`file:/User...|
|4000006|[Alice, Bob, Char...|17183869193| -99999.65|                0|        |delta.`file:/User...|
|4000007|[Alice, Bob, Char...|17183869194|  -99999.6|                0|        |delta.`file:/User...|
|4000008|[Alice, Bob, Char...|17183869195| -99999.55|                0|        |delta.`file:/User...|
|4000009|[Alice, Bob, Char...|17183869196|  -99999.5|                0|        |delta.`file:/User...|
|4000010|[Alice, Bob, Char...|17183869197| -99999.45|                0|        |delta.`file:/User...|
|4000011|[Alice, Bob, Char...|17183869198|  -99999.4|                0|        |delta.`file:/User...|
|4000012|[Alice, Bob, Char...|17183869199| -99999.35|                0|        |delta.`file:/User...|
|4000013|[Alice, Bob, Char...|17183869200|  -99999.3|                0|        |delta.`file:/User...|
|4000014|[Alice, Bob, Char...|17183869201| -99999.25|                0|        |delta.`file:/User...|
|4000015|[Alice, Bob, Char...|17183869202|  -99999.2|                0|        |delta.`file:/User...|
|4000016|[Alice, Bob, Char...|17183869203| -99999.15|                0|        |delta.`file:/User...|
|4000017|[Alice, Bob, Char...|17183869204|  -99999.1|                0|        |delta.`file:/User...|
|4000018|[Alice, Bob, Char...|17183869205| -99999.05|                0|        |delta.`file:/User...|
|4000019|[Alice, Bob, Char...|17183869206|  -99999.0|                0|        |delta.`file:/User...|
+-------+--------------------+-----------+----------+-----------------+--------+--------------------+
only showing top 20 rows
Response time: 0.6701507568359375 ms

In [ ]:
%%jsoniq -u -t
delete delta-file("foobar")[$$.foo eq 15000000] from collection

Updates applied successfully.
Response time: 1.5392799377441406 ms

In [ ]:
%%jsoniq -df -t
delta-file("foobar")

+-------+--------------------+-----------+----------+-----------------+--------+--------------------+
|    foo|                 bar|    __rowID|__rowOrder|__mutabilityLevel|__pathIn|     __tableLocation|
+-------+--------------------+-----------+----------+-----------------+--------+--------------------+
|4000000|[Alice, Bob, Char...|17183869187| -99999.95|                0|        |delta.`file:/User...|
|4000001|[Alice, Bob, Char...|17183869188|  -99999.9|                0|        |delta.`file:/User...|
|4000002|[Alice, Bob, Char...|17183869189| -99999.85|                0|        |delta.`file:/User...|
|4000003|[Alice, Bob, Char...|17183869190|  -99999.8|                0|        |delta.`file:/User...|
|4000004|[Alice, Bob, Char...|17183869191| -99999.75|                0|        |delta.`file:/User...|
|4000005|[Alice, Bob, Char...|17183869192|  -99999.7|                0|        |delta.`file:/User...|
|4000006|[Alice, Bob, Char...|17183869193| -99999.65|                0|        |delta.`file:/User...|
|4000007|[Alice, Bob, Char...|17183869194|  -99999.6|                0|        |delta.`file:/User...|
|4000008|[Alice, Bob, Char...|17183869195| -99999.55|                0|        |delta.`file:/User...|
|4000009|[Alice, Bob, Char...|17183869196|  -99999.5|                0|        |delta.`file:/User...|
|4000010|[Alice, Bob, Char...|17183869197| -99999.45|                0|        |delta.`file:/User...|
|4000011|[Alice, Bob, Char...|17183869198|  -99999.4|                0|        |delta.`file:/User...|
|4000012|[Alice, Bob, Char...|17183869199| -99999.35|                0|        |delta.`file:/User...|
|4000013|[Alice, Bob, Char...|17183869200|  -99999.3|                0|        |delta.`file:/User...|
|4000014|[Alice, Bob, Char...|17183869201| -99999.25|                0|        |delta.`file:/User...|
|4000015|[Alice, Bob, Char...|17183869202|  -99999.2|                0|        |delta.`file:/User...|
|4000016|[Alice, Bob, Char...|17183869203| -99999.15|                0|        |delta.`file:/User...|
|4000017|[Alice, Bob, Char...|17183869204|  -99999.1|                0|        |delta.`file:/User...|
|4000018|[Alice, Bob, Char...|17183869205| -99999.05|                0|        |delta.`file:/User...|
|4000019|[Alice, Bob, Char...|17183869206|  -99999.0|                0|        |delta.`file:/User...|
+-------+--------------------+-----------+----------+-----------------+--------+--------------------+
only showing top 20 rows
Response time: 0.5831758975982666 ms

In [ ]:
%%jsoniq -u -t
edit delta-file("foobar")[$$.foo eq 1400000] into { "foo" : 17000000, "bar" : [ "Alice", "Bob", "Daniel" ] } in collection

Updates applied successfully.
Response time: 1.647326946258545 ms

In [ ]:
%%jsoniq -df -t
delta-file("foobar")

+-------+--------------------+-----------+----------+-----------------+--------+--------------------+
|    foo|                 bar|    __rowID|__rowOrder|__mutabilityLevel|__pathIn|     __tableLocation|
+-------+--------------------+-----------+----------+-----------------+--------+--------------------+
|4000000|[Alice, Bob, Char...|17183869187| -99999.95|                0|        |delta.`file:/User...|
|4000001|[Alice, Bob, Char...|17183869188|  -99999.9|                0|        |delta.`file:/User...|
|4000002|[Alice, Bob, Char...|17183869189| -99999.85|                0|        |delta.`file:/User...|
|4000003|[Alice, Bob, Char...|17183869190|  -99999.8|                0|        |delta.`file:/User...|
|4000004|[Alice, Bob, Char...|17183869191| -99999.75|                0|        |delta.`file:/User...|
|4000005|[Alice, Bob, Char...|17183869192|  -99999.7|                0|        |delta.`file:/User...|
|4000006|[Alice, Bob, Char...|17183869193| -99999.65|                0|        |delta.`file:/User...|
|4000007|[Alice, Bob, Char...|17183869194|  -99999.6|                0|        |delta.`file:/User...|
|4000008|[Alice, Bob, Char...|17183869195| -99999.55|                0|        |delta.`file:/User...|
|4000009|[Alice, Bob, Char...|17183869196|  -99999.5|                0|        |delta.`file:/User...|
|4000010|[Alice, Bob, Char...|17183869197| -99999.45|                0|        |delta.`file:/User...|
|4000011|[Alice, Bob, Char...|17183869198|  -99999.4|                0|        |delta.`file:/User...|
|4000012|[Alice, Bob, Char...|17183869199| -99999.35|                0|        |delta.`file:/User...|
|4000013|[Alice, Bob, Char...|17183869200|  -99999.3|                0|        |delta.`file:/User...|
|4000014|[Alice, Bob, Char...|17183869201| -99999.25|                0|        |delta.`file:/User...|
|4000015|[Alice, Bob, Char...|17183869202|  -99999.2|                0|        |delta.`file:/User...|
|4000016|[Alice, Bob, Char...|17183869203| -99999.15|                0|        |delta.`file:/User...|
|4000017|[Alice, Bob, Char...|17183869204|  -99999.1|                0|        |delta.`file:/User...|
|4000018|[Alice, Bob, Char...|17183869205| -99999.05|                0|        |delta.`file:/User...|
|4000019|[Alice, Bob, Char...|17183869206|  -99999.0|                0|        |delta.`file:/User...|
+-------+--------------------+-----------+----------+-----------------+--------+--------------------+
only showing top 20 rows
Response time: 0.5863802433013916 ms

In [ ]:
%%jsoniq -u -t
delete collection delta-file("foobar")

Updates applied successfully.
Response time: 0.03163290023803711 ms